name: deploy website
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          now-org-id: ${{ secrets.ORG_ID}}  #Required
          now-project-id: ${{ secrets.PROJECT_ID}} #Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          # zeit-team-id: team_XXXXXXXXXXX #Optional
          # now-args: '--prod' #Optional
